### PR TITLE
Add extra details about `json-loader` and rules

### PR DESCRIPTION
**Pull request by samtsai**
This came out of reviewing parts of issue 35

### CODE REVIEW

**Comment by flootr** [comment]
Thanks for your PR @samtsai! I'd like to wait with merging this until we _"officially"_ support webpack 2 (it should work, but tests run on webpack 1). If you want, you could also create a PR and update the tests to use webpack 2 and related configuration.

**Comment by samtsai** [comment]
@flootr cool, that makes sense, yea I'll get that ready

**Comment by samtsai** [comment]
@flootr should be good to go when you're ready to make the official upgrade. Nothing major has changed in your implementation :)

**Comment by samtsai** [comment]
Looks like `webpack2` has dropped support of Node v0.12 and below to meet the Node EOL for those versions (see https://github.com/nodejs/LTS)

**Comment by flootr** [comment]
@samtsai could you back-merge the current master? The build then shouldn't fail anymore and we can finally merge your PR 🎉

**Comment by samtsai** [comment]
@flootr sure thing, trying it out now, looks like still some issues but let me investigate

**Comment by samtsai** [comment]
As you might be seeing, I'm trying to debug the failing tests. At one point I was able to reproduce locally but now they're passing locally and failing on Travis again...

The initial issue was it couldn't resolve the fixture path, so it had no entry file. Still working on it.

Once I resolve I'll clean up the commit history.

**Comment by samtsai** [comment]
@flootr looks better now! Phew, I think I was having issues because I didn't push the updated `package-lock.json`.

**Comment by flootr** [comment]
Thank you so much @samtsai for the time you invested 💐

**Pull request merged**
