### PR TITLE
docs: improve README file

### PR DESCRIPTION
**Pull request by jmarceli**
Add Modernizr options link and rearrange instructions.

### CODE REVIEW

**Comment by flootr** [comment]
lgtm 

@jhnns ?

**Comment by jhnns** [comment]
Thx @jmarceli. I think, we should remove the example 

``` javascript
require("!modernizr!./.modernizrrc")
// => returns compiled modernizr build based on your configuration
```

because it does not make sense in this context anymore because before this example, we explain how to configure the loader. And after doing that, you don't need to prepend it with `!modernizr!` anymore. I think we should just remove it, the next ES2015 example is sufficient.

**Comment by jmarceli** [comment]
I've removed `require` info from README but I was having some issues #13  with ES6 import so maybe we should still mention somewhere about require alternative?

**Comment by jhnns** [comment]
Thx 👍

**Pull request merged**
